Simple translation
ONSdigital/dis-wagtail-alpha pull request #40
Opened 2024-08-15 08:21 UTC by zerolab

Enables and configures i18n.
- uses a path prefix for the language
- adds a language switcher
- adds some string translations (extracted from our apps/templates)

Screencast: https://www.loom.com/share/064b91f042ec4968af5ddbb69f9fe3af?sid=5b8efee8-ecb1-4133-a427-0aba43649d42

2024-08-16 10:42 UTC, MebinAbraham requested changes
Few things to things to address:

1. The README should be updated to document how to generate the .po file and then compile to get the .mo file.
2. Since the translations create new pages that represent the same thing, the topic page now errors due to our validation of 'Topic section page with this Topic already exists.'. We would need would need to handle this this for translated pages unless we allow translating topic's themselves. How have you normally handled situation like this before, especially 1:1 relationships?.
3. Current previewing of bulletings are erroring on to the following lines https://github.com/ONSdigital/dis-wagtail-alpha/pull/40/files#diff-107bebabb3ec5a591b296fe91fe34ba6906fb78d5dac4639722124b3949c4b96R48-R49
    - variant is returning None, hence falling over when using `get_url` on `NoneType`.

2024-08-20 14:46 UTC, RealOrangeOne commented
I wasn't able to find a solution for changing slug breaking page serving. The links are still correct, but the page isn't accessible at the new slug, only the old. I'm not especially familiar with Wagtail's internationalisation internals, to know where the bug in this might lie, so I'd suggest waiting for Dan's return.

2024-09-03 16:38 UTC, zerolab commented
So the issue in the S&T was with the fact that the Welsh tree root page (homepage) was unpublished. Once you publish it, all works. Definitely a Wagtail peculiarity.

Now going down into the weeds debugging Wagtail core.

2024-09-04 09:53 UTC, MebinAbraham approved these changes

2024-09-04 09:53 UTC, MebinAbraham commented on .editorconfig
> +indent_style = tag
```suggestion
indent_style = tab
```

2024-09-04 09:53 UTC, MebinAbraham commented on Makefile
> +	python -m manage makemessages --all
```suggestion
	poetry run python -m manage makemessages --all
```

2024-09-04 09:53 UTC, MebinAbraham commented on Makefile
> +	python -m manage compilemessages --use-fuzzy
```suggestion
	poetry run python -m manage compilemessages --use-fuzzy
```

2024-09-06 08:53 UTC, merged