Add Linters and CI Setup
ONSdigital/dis-wagtail-alpha pull request #5
Opened 2024-06-27 09:06 UTC by islas104

This pull request introduces linters (Ruff, pylint, black) and a continuous integration setup using GitHub Actions.

**Key Changes:**
Added Makefile commands for linting and formatting.
Updated README.md with detailed instructions on how to install and use the linters.
Created a GitHub Actions workflow (linting.yml) to run linters and build the Docker image on push and pull request events.
Ensured dependencies are installed via poetry.
Verified the Docker image can be built to ensure no breaking changes.
These changes improve code quality and consistency across the project, making it easier for new contributors to set up and maintain the development environment.

Please review and let me know if there are any issues or further improvements needed. Thank you!

2024-06-27 09:22 UTC, zerolab requested changes
Did a first pass review. Good start. Needs a bit more work.

2024-06-27 09:22 UTC, zerolab commented on pyproject.toml
> +[tool.poetry.group.dev.dependencies]
question: is this an accidental paste? Line 32 already has it

2024-06-27 09:22 UTC, zerolab commented on ons_alpha/github/linting.yml
> +name: Linting and Formatting
note: this should be in `.github/workflows/linting.yml` for GitHub Actions to pick it up.

2024-06-27 09:22 UTC, zerolab commented on ons_alpha/Makefile
> +    poetry run black .
question: both black and ruff use the current directory (the repository root) whereas pylint only looks at the app directory (`ons_alpha`). Should they not all look at the same set of files?

2024-06-27 09:22 UTC, zerolab commented on README.md
> +Create a workflow file named `linting.yml` in the `.github/workflows` directory with the following content:
suggestion: drop this paragraph, the yaml example, and the conclusion section. They are not relevant to the README

2024-06-27 09:22 UTC, zerolab commented on ons_alpha/github/workflows
> +name: Linting and Formatting
this file is extraneous and does nothing

2024-06-27 09:22 UTC, zerolab commented on pyproject.toml
> +pylint = "^3.2.4"
there is no pylint configuration

2024-06-27 09:23 UTC, zerolab commented on ons_alpha/github/linting.yml
> +name: Linting and Formatting
note that there is some linting in https://github.com/torchbox/ons-alpha/blob/main/.github/workflows/ci.yml#L12-L89 which could either be removed, or replaced

2024-06-27 09:24 UTC, zerolab commented on ons_alpha/github/linting.yml
> +      run: docker run --rm ons-alpha some-command-to-verify
note: this will fail when run by GitHub Actions unless `some-commad-to-verify` is replaced with something functional

2024-06-27 09:34 UTC, MebinAbraham commented on Makefile
> +	poetry run pylint ons_alpha
Missing black.

2024-06-27 09:34 UTC, MebinAbraham commented on Makefile
> +	poetry run ruff .
Will this not run both ruff lint and format?. We should use `ruff check`, we don't want to format via ruff yet, we should use black for now for format checks.

2024-06-27 09:34 UTC, MebinAbraham commented on ons_alpha/github/linting.yml
> +          python-version: '3.12'
Add and use a `.python-version` file. See existing pattern in https://github.com/ONSdigital/ons-python-template-demo/blob/main/.github/workflows/ci.yml#L23-L27

2024-06-27 09:34 UTC, MebinAbraham commented on ons_alpha/github/linting.yml
> +        run: poetry run black --check .
We should re-use the Makefile commands here so we have a single place where they are defined. Here we should be calling `make lint` and `make format`

2024-06-27 09:34 UTC, MebinAbraham commented on pyproject.toml
> +pylint = "^3.2.4"
Worth using https://github.com/ONSdigital/ons-python-template-demo/blob/main/.pylintrc and modify as needed for this project.

2024-06-27 09:36 UTC, MebinAbraham commented on Makefile
> +	poetry run black .
Here we can also do lint fixes from ruff using `poetry run ruff check . --fix`

2024-06-27 11:24 UTC, zerolab commented on README.md
> +### GitHub Actions Workflow
this section is not needed since we have `.github/workflows/linting.yml`

2024-06-27 11:25 UTC, zerolab commented on ons_alpha/Makefile
> +    poetry run black .
there is a Makefile in the repository root. This one is obsolete

2024-06-27 11:26 UTC, zerolab commented on .github/ci.yml
question: why this move?
if the goal is to not use it, then it is best to remove all together

2024-06-27 11:27 UTC, zerolab commented on .github/linting.yml
> +name: Linting, Formatting, and Docker Build
this needs to be in `.github/workflows/` for GitHub Actions to pick it up

2024-06-27 11:27 UTC, zerolab commented on .pylintry
> +[MAIN]
the pylint configuration file is `.pylintrc`. You have `.pylintry` and `.pylintrcy` so neither is picked up

2024-06-27 12:49 UTC, islas104 commented on ons_alpha/Makefile
> +    poetry run black .
Thank you for the feedback. I have made the necessary adjustments to ensure that black, ruff, and pylint all target the same directory (the repository root) for consistency. Additionally, I have ensured that there is only one Makefile in the repository root which is now updated and no longer obsolete.

2024-06-27 12:59 UTC, islas104 commented on pyproject.toml
> +pylint = "^3.2.4"
Thank you for the feedback. I have added a pylintrc configuration file to the project. The pylintrc is based on the one from the ONSdigital/ons-python-template-demo repository and has been modified as needed for our project.

2024-06-27 13:01 UTC, islas104 commented on Makefile
> +	poetry run pylint ons_alpha
This has been added now.

2024-06-27 13:02 UTC, islas104 commented on Makefile
> +	poetry run ruff .
Thank you for pointing that out. I've updated the Makefile to ensure that ruff is used only for linting (not formatting), and that black is used for formatting checks.

2024-06-27 13:07 UTC, islas104 commented on ons_alpha/github/linting.yml
> +          python-version: '3.12'
Thank you for the suggestion. I have added a .python-version file and updated the GitHub Actions workflow to use this file for setting up the Python version.

2024-06-27 13:09 UTC, islas104 commented on ons_alpha/github/linting.yml
> +        run: poetry run black --check .
Thank you for the suggestion. I have updated the linting.yml workflow to reuse the Makefile commands for consistency.

2024-06-27 13:27 UTC, islas104 commented on .pylintry
> +[MAIN]
Thank you for pointing that out. I've corrected the Pylint configuration file name. The file is now properly named .pylintrc in the root directory.

2024-06-27 13:38 UTC, zerolab commented on .github/linting.yml
> +name: Linting, Formatting, and Docker Build
the path for this file is still `.github/linting.yml`. it should be `.github/workflows/linting.yml`

2024-06-27 13:38 UTC, zerolab commented on .pylintry
> +[MAIN]
@islas104 are you sure you've pushed your changes? I see the same 2 files, not `.pylintrc`

2024-06-27 13:40 UTC, zerolab commented on ons_alpha/Makefile
> +>>>>>>> 9070f18 (Update Readme.md file with verified commit)
can you please remove `ons_alpha/Makefile` leaving just the `Makefile` in the repository root?

2024-06-27 17:28 UTC, islas104 commented on .github/linting.yml
> +name: Linting, Formatting, and Docker Build
This has been addressed in the latest commit, thank you.

2024-06-27 17:29 UTC, islas104 commented on .pylintry
> +[MAIN]
@zerolab  - This has been pushed across, please see latest commit.

2024-06-27 17:43 UTC, islas104 commented on ons_alpha/Makefile
> +>>>>>>> 9070f18 (Update Readme.md file with verified commit)
@zerolab  - Done.

2024-07-02 15:08 UTC, zerolab commented on Makefile
> +	find . -type f -name "*.py" | xargs poetry run pylint --reports=n --output-format=colorized --rcfile=.pylintrc -j 0
it would be nice to add `pylint` to the pre-commit config, but that can come in a separate PR/later

2024-07-02 15:09 UTC, zerolab commented on ons_alpha/settings/base.py
> +    / "assets"
This is one of the things that ruff diverges from black on, and I am with ruff on it.

2024-07-02 15:11 UTC, zerolab approved these changes
LGTM

2024-07-02 16:00 UTC, MebinAbraham commented on Makefile
> +	find . -type f -name "*.py" | xargs poetry run pylint --reports=n --output-format=colorized --rcfile=.pylintrc -j 0
I'll raise a separate PR to update pre commit config to be consistent with our linters.

2024-07-02 16:01 UTC, merged