Bulletin pages
ONSdigital/dis-wagtail-alpha pull request #7
Opened 2024-07-01 10:35 UTC by RealOrangeOne

https://jira.ons.gov.uk/browse/NWP-145

Adds a skeleton bulletin page (with related topic and topic section pages).

The content is mostly placeholders to be used to build out content. Basic blocks exist. The notably missing areas are "Related links", Citations, table downloads, charts.

2024-07-02 09:23 UTC, zerolab commented on ons_alpha/jinja2/templates/components/streamfield/stream_block.html
> -{% for block in value %}
please leave this as I am using it in #8

2024-07-02 09:25 UTC, zerolab commented on ons_alpha/jinja2/templates/pages/topics/topic_section_page.html
> +{% extends "templates/base_page.html" %}
please re-use the standard index template. it has a good enough starting point

2024-07-02 10:24 UTC, RealOrangeOne commented on ons_alpha/jinja2/templates/components/streamfield/stream_block.html
> -{% for block in value %}
We've gone in different directions. I've used a list of blocks and used `include_blocks`, whilst you've used a struct block to store which blocks are valid. I'm not sure what the best implementation is?

2024-07-02 10:31 UTC, zerolab commented on ons_alpha/jinja2/templates/components/streamfield/stream_block.html
> -{% for block in value %}
Both implementations are valid. I am more in favour of defining `StreamBlock`s as usually we have more than a few block types

2024-07-02 11:41 UTC, RealOrangeOne commented on ons_alpha/jinja2/templates/components/streamfield/stream_block.html
> -{% for block in value %}
I guess the main benefit of that approach is it lets us reuse the same block set on multiple models more easily. I'll port mine.

2024-07-02 15:28 UTC, RealOrangeOne commented on ons_alpha/jinja2/templates/components/streamfield/stream_block.html
> -{% for block in value %}
I've swapped to using a `StreamBlock`, but even then this template isn't necessary - looping through and rendering each block is the default, and removing the template removes the jinja overhead.

2024-07-02 15:38 UTC, zerolab commented on ons_alpha/jinja2/templates/components/streamfield/panel_block.html
> +"variant": value.variant,
you can wrap these with `{# fmt:off #}` / `{# fmt:on #}` to prevent djhtml messing them up

2024-07-02 15:39 UTC, RealOrangeOne commented on ons_alpha/jinja2/templates/components/streamfield/panel_block.html
> +"variant": value.variant,
`djhtml` has an oddly hard time with funky indentation. Yeah that makes things much clearer!

2024-07-02 16:03 UTC, zerolab requested changes

2024-07-02 16:03 UTC, zerolab commented on ons_alpha/bulletins/blocks.py
> +    table = TableBlock()
bulletins do use images, as well as embedded videos at times, so `ImageBlock`/`EmbedBlock` from the old core blocks would be useful here.

Looking at this.. I want us to keep the information page and the index page models, even if they are not strictly part of the the thin slice

2024-07-02 16:03 UTC, zerolab commented on ons_alpha/core/blocks/markup.py
> +        template = "templates/components/streamfield/heading_block.html"
```suggestion
        icon = "title"
        template = "templates/components/streamfield/heading_block.html"
```

2024-07-02 16:03 UTC, zerolab commented on ons_alpha/core/blocks/panels.py
> +        template = "templates/components/streamfield/panel_block.html"
note: best to add icons for all SF blocks.. makes for a nicer editorial experience (and our goal is to delight). can be done as a follow up when we add related links, for example

2024-07-02 16:03 UTC, zerolab commented on ons_alpha/core/models/mixins.py
> +    PAGE_SIZE = 24
question: why 24? :)
and should this not be configurable via settings?

2024-07-02 16:03 UTC, zerolab commented on ons_alpha/core/templatetags/tableofcontents.py
> +def table_of_contents(context, page, attr_name, options=None):
note to self: in a future piece of work we should rename this to `table_of_contents_from_streamfield`

also looking at https://service-manual.ons.gov.uk/design-system/components/table-of-contents we could probably use the "In-page table of contents" variant where `{"lists": [{"itemsList": ...}` is replaced by `{"itemsList":...}`

2024-07-03 08:30 UTC, RealOrangeOne commented on ons_alpha/core/models/mixins.py
> +    PAGE_SIZE = 24
The designs I saw used 3 columns, so 24 gives a reasonable number of cards before paginating.

It's configurable per-page by just setting `PAGE_SIZE` on it. I wouldn't say it needs to be a Django setting.

2024-07-03 09:31 UTC, zerolab commented
Needs a rebase on main. and a `make format`

2024-07-03 13:15 UTC, zerolab approved these changes
Will merge this, then follow up with a PR for a few of the missing elements.

2024-07-03 13:16 UTC, merged